spring.application.name=VMS-AUTH

spring.datasource.url=${DB_URL_AUTH}
spring.datasource.username=${NEON_USERNAME}
spring.datasource.password=${NEON_PASSWORD}


eureka.instance.prefer-ip-address=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
