spring.application.name=VMS-PERFORMANCE
spring.datasource.url=${DB_URL_PERFORMANCE}
spring.datasource.username=${NEON_USERNAME}
spring.datasource.password=${NEON_PASSWORD}

spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.max-lifetime=60000
spring.datasource.hikari.connection-timeout=30000
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
